parameters:
#    mardraze_product.example.class: Mardraze\ProductBundle\Example

services:
#    mardraze_product.example:
#        class: %mardraze_product.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
